#!/usr/bin/env bash

# Check that local time is the same on all nodes in a Quobyte cluster.

# Stop the script when a command fails.
set -e

# Stop the script when a pipeline fails.
set -o pipefail

# Forbid the use of unset variables in string substitutions.
set -u

# Get openstack credentials
. /etc/openstack/nova-openrc.sh

# start prometheus-libvirt-exporter
python3 /usr/bin/libvirt_exporter.py 
